In [10]:
import pandas as pd

A2 = pd.read_excel('A2.xlsx')

In [11]:
A2['카드승인일자_1']

0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
             ...
167097    2023-05-25
167098    2023-05-26
167099    2023-05-26
167100    2023-05-31
167101    2023-05-31
Name: 카드승인일자_1, Length: 167102, dtype: object

In [12]:
A2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167102 entries, 0 to 167101
Data columns (total 62 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   증권번호          167102 non-null  int64
 1   임직원여부         1768 non-null    object
 2   유입처순번         167102 non-null  int64
 3   유입일시          161497 non-null  datetime64[ns]
 4   유입채널디바이스구분    167102 non-null  object
 5   유입채널대분류명      167102 non-null  object
 6   유입채널중분류명      167102 non-null  object
 7   매체명           167102 non-null  object
 8   유입처코드         161497 non-null  float64
 9   유입처명          161688 non-null  object
 10  계약일자          167102 non-null  object
 11  초회영수일자        167102 non-null  object
 12  상품채널구분        167102 non-null  object
 13  신규갱신구분        167102 non-null  object
 14  신규갱신상세구분      163397 non-null  object
 15  신차구분_다이렉트     167102 non-null  object
 16  상품코드          167102 non-null  int64
 17  상품명           167102 non-null  object
 18  공동인수여부        167102 non-null  object
 19  보험시작일자        167102 non-null  object
 20  보험종료일자        167102 non-null  object
 21  피보험자법인구분      167102 non-null  object
 22  피보험자고객번호      167102 non-null  int64
 23  피보험자주민번호      167102 non-null  object
 24  피보험자명         167102 non-null  object
 25  계약자고객번호       167102 non-null  int64
 26  계약자주민번호       167102 non-null  object
 27  계약자명          167102 non-null  object
 28  센터명           167102 non-null  object
 29  최종취급자사원번호     167102 non-null  int64
 30  취급자명          167102 non-null  object
 31  초회적용보험료       167102 non-null  int64
 32  차량번호          166247 non-null  object
 33  피보험자전화일련번호    158859 non-null  object
 34  결제방법          167102 non-null  object
 35  카드사_1         136465 non-null  object
 36  카드번호_1        136465 non-null  object
 37  카드승인일자_1      136465 non-null  object
 38  가맹점상세_1       136465 non-null  object
 39  가맹점코드_1       136465 non-null  object
 40  카드승인번호_1      136465 non-null  float64
 41  카드승인금액_1      136465 non-null  float64
 42  카드사_2         123 non-null     object
 43  카드번호_2        123 non-null     object
 44  카드승인일자_2      123 non-null     object
 45  가맹점상세_2       123 non-null     object
 46  가맹점코드_2       123 non-null     object
 47  카드승인번호_2      123 non-null     float64
 48  카드승인금액_2      123 non-null     float64
 49  포인트결제명        28155 non-null   object
 50  포인트승인금액       28155 non-null   float64
 51  앱카드정보_스마일페이   246 non-null     object
 52  주문번호          9175 non-null    object
 53  페이결제번호        9175 non-null    object
 54  최초청약번호        167102 non-null  object
 55  연료구분          167102 non-null  object
 56  정산대상          167102 non-null  object
 57  최종유입처코드       156640 non-null  float64
 58  피보험자_임직원      1533 non-null    object
 59  계약자_임직원       1554 non-null    object
 60  다이렉트제휴회사고객번호  5928 non-null    object
 61  티맵할인특약가입여부    167102 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(7), object(47)
memory usage: 79.0+ MB

In [13]:
A2['카드승인일자_1'] = pd.to_datetime(A2['카드승인일자_1'])

A2['카드승인일자_2'] = pd.to_datetime(A2['카드승인일자_2'])

In [14]:
A2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167102 entries, 0 to 167101
Data columns (total 62 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   증권번호          167102 non-null  int64
 1   임직원여부         1768 non-null    object
 2   유입처순번         167102 non-null  int64
 3   유입일시          161497 non-null  datetime64[ns]
 4   유입채널디바이스구분    167102 non-null  object
 5   유입채널대분류명      167102 non-null  object
 6   유입채널중분류명      167102 non-null  object
 7   매체명           167102 non-null  object
 8   유입처코드         161497 non-null  float64
 9   유입처명          161688 non-null  object
 10  계약일자          167102 non-null  object
 11  초회영수일자        167102 non-null  object
 12  상품채널구분        167102 non-null  object
 13  신규갱신구분        167102 non-null  object
 14  신규갱신상세구분      163397 non-null  object
 15  신차구분_다이렉트     167102 non-null  object
 16  상품코드          167102 non-null  int64
 17  상품명           167102 non-null  object
 18  공동인수여부        167102 non-null  object
 19  보험시작일자        167102 non-null  object
 20  보험종료일자        167102 non-null  object
 21  피보험자법인구분      167102 non-null  object
 22  피보험자고객번호      167102 non-null  int64
 23  피보험자주민번호      167102 non-null  object
 24  피보험자명         167102 non-null  object
 25  계약자고객번호       167102 non-null  int64
 26  계약자주민번호       167102 non-null  object
 27  계약자명          167102 non-null  object
 28  센터명           167102 non-null  object
 29  최종취급자사원번호     167102 non-null  int64
 30  취급자명          167102 non-null  object
 31  초회적용보험료       167102 non-null  int64
 32  차량번호          166247 non-null  object
 33  피보험자전화일련번호    158859 non-null  object
 34  결제방법          167102 non-null  object
 35  카드사_1         136465 non-null  object
 36  카드번호_1        136465 non-null  object
 37  카드승인일자_1      136465 non-null  datetime64[ns]
 38  가맹점상세_1       136465 non-null  object
 39  가맹점코드_1       136465 non-null  object
 40  카드승인번호_1      136465 non-null  float64
 41  카드승인금액_1      136465 non-null  float64
 42  카드사_2         123 non-null     object
 43  카드번호_2        123 non-null     object
 44  카드승인일자_2      123 non-null     datetime64[ns]
 45  가맹점상세_2       123 non-null     object
 46  가맹점코드_2       123 non-null     object
 47  카드승인번호_2      123 non-null     float64
 48  카드승인금액_2      123 non-null     float64
 49  포인트결제명        28155 non-null   object
 50  포인트승인금액       28155 non-null   float64
 51  앱카드정보_스마일페이   246 non-null     object
 52  주문번호          9175 non-null    object
 53  페이결제번호        9175 non-null    object
 54  최초청약번호        167102 non-null  object
 55  연료구분          167102 non-null  object
 56  정산대상          167102 non-null  object
 57  최종유입처코드       156640 non-null  float64
 58  피보험자_임직원      1533 non-null    object
 59  계약자_임직원       1554 non-null    object
 60  다이렉트제휴회사고객번호  5928 non-null    object
 61  티맵할인특약가입여부    167102 non-null  object
dtypes: datetime64[ns](3), float64(7), int64(7), object(45)
memory usage: 79.0+ MB

In [15]:
A2_test = A2[A2['카드승인일자_1'].between('2023-05-01', '2023-05-09') | A2['카드승인일자_2'].between('2023-05-01', '2023-05-09')]
A2_test

,증권번호,임직원여부,유입처순번,유입일시,유입채널디바이스구분,유입채널대분류명,유입채널중분류명,매체명,유입처코드,유입처명,...,주문번호,페이결제번호,최초청약번호,연료구분,정산대상,최종유입처코드,피보험자_임직원,계약자_임직원,다이렉트제휴회사고객번호,티맵할인특약가입여부
227,20232453291,NaN,1,2023-04-30 23:53:02,Mobile,광고,광고_SA_BS,Naver,1.090038e+10,Naver BS(M메인_메뉴1),...,NaN,NaN,RQ2320370488,LPG,N,1.090038e+10,NaN,NaN,NaN,N
228,20232453292,NaN,1,2023-04-30 23:45:04,MobileApp,직접유입,직접유입_대표,직접유입(W/M),1.090036e+10,web 직접유입,...,NaN,NaN,RQ2320371428,가솔린,Y,1.090036e+10,NaN,NaN,NaN,N
229,20232453293,NaN,1,2023-04-30 23:55:43,MobileApp,직접유입,직접유입_대표,직접유입(W/M),1.090036e+10,web 직접유입,...,NaN,NaN,RQ2320371861,디젤,N,1.090036e+10,NaN,NaN,NaN,Y
230,20232453294,NaN,1,2023-04-30 23:51:25,Web,광고,광고_SA,Naver,1.090038e+10,NVC1_(KB자동차보험다이렉트),...,NaN,NaN,RQ2315733693,가솔린,Y,1.090038e+10,NaN,NaN,NaN,Y
231,20232453295,NaN,1,NaT,기타,기타,기타,유입처확인불가,NaN,NaN,...,NaN,NaN,RQ2320371774,가솔린,N,1.090036e+10,NaN,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63957,20232701478,NaN,1,2023-05-04 14:31:58,Call,직접유입,직접유입_대표,직접유입(Call),1.000000e+00,1번 가입문의(1544-0077),...,NaN,NaN,RQ2321130854,디젤,Y,1.000000e+00,NaN,NaN,NaN,N
74753,20232728836,NaN,1,2023-05-09 16:03:27,Call,기타,기타_센터전용,장기,2.970000e+02,TSR1전용(1833-3815),...,NaN,NaN,RQ2322107581,가솔린,N,1.528000e+03,NaN,NaN,NaN,N
75941,20232734194,NaN,1,2023-05-02 15:40:20,Call,직접유입,직접유입_대표,고객콜센터,8.400000e+01,자동차(다이렉트) 가입문의(1544-0114),...,NaN,NaN,RQ2320634336,LPG,Y,8.400000e+01,NaN,NaN,NaN,N
93960,20232808635,NaN,1,2023-05-08 15:27:58,Call,직접유입,직접유입_대표,직접유입(Call),1.950000e+02,CM상품 가입문의(1544-8516),...,NaN,NaN,RQ2321860161,디젤,Y,1.950000e+02,NaN,NaN,NaN,Y
126096,20232932649,NaN,1,2023-05-24 10:54:32,Call,제휴,제휴,차봇,2.330000e+02,차봇(1644-4396),...,NaN,NaN,RQ2321085747,가솔린,Y,1.430000e+03,NaN,NaN,NaN,N